config/routes.rb
Rails.application.routes.draw do
  root to: "clip_posts#index"
  # Sitemap
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/clipreactor/sitemaps/sitemap.xml.gz')

  
  # Test Controller
  get 'test', to: 'test#new'

  # Clip Posts
  resources :clip_posts do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get :likes
      get :get_clip
      get :update_video
    end
  end

  # Tags
  resources :tags do
    collection do
      get :auto_complete_streamers
      get :auto_complete_tags
    end
  end

  # Users
  resources :users, only: %i[new create] do
    collection do
      get :get_user_stamp
    end
  end

  # Likes and Comment Likes
  resources :likes, only: %i[create destroy]
  resources :comment_likes, only: %i[create destroy]

  # Static Pages
  get 'terms', to: 'satatic_pages#terms'
  get 'privacy_policy', to: 'satatic_pages#privacy_policy'

  # Contacts
  get 'contact', to: 'contacts#new'
  post 'contact', to: 'contacts#create'
  get 'contact/success', to: 'contacts#success'

  # User Sessions
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :clip_posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_clip_posts, through: :likes, source: :clip_post
  has_many :comments, dependent: :destroy
  has_many :comment_likes, dependent: :destroy
  has_many :comment_like_comments, through: :comment_likes, source: :comment
  has_many :view_histories, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :password, confirmation: true
  validates :password, presence: true, length: { minimum: 4 }

  def own?(object)
    id == object.user_id
  end

  def like(clip_post)
    like_clip_posts << clip_post
  end

  def unlike(clip_post)
    like_clip_posts.destroy(clip_post)
  end

  def like?(clip_post)
    like_clip_posts.include?(clip_post)
  end

  def comment_like(comment)
    comment_like_comments << comment
  end

  def comment_unlike(comment)
    comment_like_comments.destroy(comment)
  end

  def comment_like?(comment)
    comment_like_comments.include?(comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create get_user_stamp]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to clip_posts_path, success: '登録ありがとネ'
    else
      flash.now[:danger] = '登録失敗しちゃったヨ'
      render :new
    end
  end

  def get_user_stamp
    stamp_id = Image.find_by(name: params[:streamer_name]).image_id
    stamp_data = TwitchApi.new.get_stamp(stamp_id)
    random_stamp = stamp_data["data"].sample

    template = "https://static-cdn.jtvnw.net/emoticons/v2/{id}/{format}/{theme_mode}/3.0"
    data = {
      id: random_stamp["id"],
      format: random_stamp["format"].sample,
      theme_mode: random_stamp["theme_mode"].sample
    }

    url = template.gsub("{id}", data[:id])
                  .gsub("{format}", data[:format])
                  .gsub("{theme_mode}", data[:theme_mode])

    respond_to do |format|
      format.js { render 'get_user_stamp.js.erb', locals: { stamp_url: url } }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :stamp_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_streamer_index.html.erb
<div class="text-center mt-3">
  <h5 class="tag-list-title">ランダムユーザーアイコン</h5>
</div>
<div class="overflow-auto" style="height: 300px">
  <% ClipPost.tags_on(:streamers).order(name: :asc).each do |tag| %>
    <div class="ms-1 mt-3 bg-white">
      <%= link_to get_user_stamp_users_path(streamer_name: tag.name), class: "no-decoration row shadow-btn", remote: true do %>
        <div class="col-3">
        <% image_record = Image.find_by(name: tag.name) %>
          <% if image_record && image_record.image_url.present? %>
            <%= image_tag image_record.image_url, class: "rounded-circle", size: "50x50" %>
          <% else %>
            <%= image_tag "default.png", class: "rounded_circle", size: "50x50" %>
          <% end %>
        </div>
        <div class="col-9 h2" style="color: <%= image_record&.image_color %>;">
          <%= tag %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/get_user_stamp.js.erb
$("#stamp_url").val("<%= j stamp_url %>");
$("#stamp_image_tag").attr("src", "<%= j stamp_url %>");

app/views/users/new.html.erb
<% set_meta_tags title: "新規登録" %>
<%= render 'shared/title_bar', title: "新規登録" %>
<div class="container bg-light p-3">
  <%= form_with(model: @user, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :email, "メールアドレス", class: "form-label float-start" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :password, "パスワード", class: "form-label float-start" %>
      <%= form.password_field :password, class: "form-control"%>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, "パスワードの確認", class: "form-label float-start" %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.hidden_field :stamp_url, id: "stamp_url", value: "default.png" %>
      <%= image_tag "default.png", id: "stamp_image_tag", size: "112x112" %>
    </div>
    <div class="mb-3">
      <%= render 'streamer_index' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= form.button "アカウント作成", type: "submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>