config/routes.rb
Rails.application.routes.draw do
  root to: "clip_posts#index"
  # Sitemap
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/clipreactor/sitemaps/sitemap.xml.gz')

  
  # Test Controller
  get 'test', to: 'test#new'

  # Clip Posts
  resources :clip_posts do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get :likes
      get :get_clip
      get :update_video
    end
  end

  # Tags
  resources :tags do
    collection do
      get :auto_complete_streamers
      get :auto_complete_tags
    end
  end

  # Users
  resources :users, only: %i[new create] do
    collection do
      get :get_user_stamp
    end
  end

  # Likes and Comment Likes
  resources :likes, only: %i[create destroy]
  resources :comment_likes, only: %i[create destroy]

  # Static Pages
  get 'terms', to: 'satatic_pages#terms'
  get 'privacy_policy', to: 'satatic_pages#privacy_policy'

  # Contacts
  get 'contact', to: 'contacts#new'
  post 'contact', to: 'contacts#create'
  get 'contact/success', to: 'contacts#success'

  # User Sessions
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clip_post.rb
class ClipPost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :view_histories, dependent: :destroy

  acts_as_taggable_on :tags
  acts_as_taggable_on :streamers
  acts_as_taggable_on :games

  scope :clip_created_at, -> { order(clip_created_at: :desc) }
  scope :created_at, -> { order(created_at: :desc) }
  scope :most_views, -> { order(views: :desc) }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }
  scope :with_game, ->(tag_name) { joins(:games).where(tags: { name: tag_name }) }
  scope :with_streamer, ->(tag_name) { joins(:streamers).where(tags: { name: tag_name }) }

  validates :url, format: { with: /clip/, message: I18n.t("models.clip_post.url_not_clip") }
  validates :url, format: { with: /twitch\.tv/, message: I18n.t('models.clip_post.url_invalid_format') }

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def view_history(user)
    # 視聴履歴を保存する処理
    new_history = view_histories.new(user_id: user.id)
    # 既に視聴済みの場合、古い履歴を削除し新しい履歴を追加する
    if user.view_histories.exists?(clip_post_id: id)
      visited_history = user.view_histories.find_by(clip_post_id: id)
      visited_history.destroy
    end
    new_history.save
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :clip_post

  has_many :comment_likes, dependent: :destroy
  has_many :comment_like_users, through: :comment_likes, source: :user

  def comment_liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :clip_post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :clip_posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_clip_posts, through: :likes, source: :clip_post
  has_many :comments, dependent: :destroy
  has_many :comment_likes, dependent: :destroy
  has_many :comment_like_comments, through: :comment_likes, source: :comment
  has_many :view_histories, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :password, confirmation: true
  validates :password, presence: true, length: { minimum: 4 }

  def own?(object)
    id == object.user_id
  end

  def like(clip_post)
    like_clip_posts << clip_post
  end

  def unlike(clip_post)
    like_clip_posts.destroy(clip_post)
  end

  def like?(clip_post)
    like_clip_posts.include?(clip_post)
  end

  def comment_like(comment)
    comment_like_comments << comment
  end

  def comment_unlike(comment)
    comment_like_comments.destroy(comment)
  end

  def comment_like?(comment)
    comment_like_comments.include?(comment)
  end
end

app/models/view_history.rb
class ViewHistory < ApplicationRecord
  belongs_to :user
  belongs_to :clip_post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @clip_post = ClipPost.find(params[:clip_post_id])
    current_user.like(@clip_post)
  end

  def destroy
    @clip_post = current_user.likes.find(params[:id]).clip_post
    current_user.unlike(@clip_post)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :require_login, only: %i[index]
  require 'romaji'
  require 'romaji/core_ext/string'
  require 'levenshtein'
  # require 'miyabi'

  def index; end

  def auto_complete_streamers
    term = params[:term]
    # ローマ字変換
    term_romaji = to_roman(term)
    # それぞれのタグをローマ字変換して、条件で絞る
    matching_streamers_names = ClipPost.tags_on(:streamers)
                                       .select do |tag|
      roman_name = to_roman(tag.name)
      matching_character_count(roman_name, term_romaji) < 0.65 ||
        roman_name.include?(term_romaji)
    end
                                       .map(&:name)

    # オートコンプリートの候補としてnameを返す
    render json: matching_streamers_names
  end

  def auto_complete_tags
    term = params[:term].downcase

    matching_tags_names = ClipPost.tags_on(:tags).where('lower(name) LIKE ?', "%#{term}%").pluck(:name)

    # オートコンプリートの候補としてtitleを返す
    render json: matching_tags_names
  end

  def to_roman(text)
    text = text.downcase
    return text if text.include?('_')

    # 本来text.to_kanhira.romajiとして漢字をひらがなに変換もしたいが、heroku未対応のため漢字以外で検索する
    # また、レーベンシュタイン距離での一致検索のおかげで、精度も悪くはない。
    text.romaji
  end

  def matching_character_count(str1, str2)
    # レーベンシュタイン距離で一致する文字数をカウント
    distance = Levenshtein.distance(str1, str2)
    max_length = [str1.length, str2.length].max
    distance.to_f / max_length
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def new; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create get_user_stamp]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to clip_posts_path, success: '登録ありがとネ'
    else
      flash.now[:danger] = '登録失敗しちゃったヨ'
      render :new
    end
  end

  def get_user_stamp
    stamp_id = Image.find_by(name: params[:streamer_name]).image_id
    stamp_data = TwitchApi.new.get_stamp(stamp_id)
    random_stamp = stamp_data["data"].sample

    template = "https://static-cdn.jtvnw.net/emoticons/v2/{id}/{format}/{theme_mode}/3.0"
    data = {
      id: random_stamp["id"],
      format: random_stamp["format"].sample,
      theme_mode: random_stamp["theme_mode"].sample
    }

    url = template.gsub("{id}", data[:id])
                  .gsub("{format}", data[:format])
                  .gsub("{theme_mode}", data[:theme_mode])

    respond_to do |format|
      format.js { render 'get_user_stamp.js.erb', locals: { stamp_url: url } }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :stamp_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'twitchクリップ共有',
      title: 'ツイッチの動画をシェア検索や同時視聴や他視点検索アーカイブ検索でクリップをもっと楽しもう！',
      reverse: true,
      separator: '|', # Webサイト名とページタイトルを区切るために使用されるテキスト
      description: 'twitchクリップの他視点のアーカイブ検索ができるクリップ共有サイトです。イベント検索、配信者検索で、まだ見ぬおもしろクリップを共有しましょう!',
      keywords: 'ページキーワード', # キーワードを「,」区切りで設定する
      noindex: !Rails.env.production?,
      icon: [ # favicon、apple用アイコンを指定する
        { href: image_url('hasami-icon.ico') },
        { href: image_url('hasami-icon.ico'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' }
      ],
      og: {
        site_name: 'twitchクリップ共有',
        title: 'ツイッチの動画をシェア検索して視聴者の反応も楽しもう！',
        description: 'お気に入りクリップを共有しましょう！ゲーム検索・イベント名検索で埋もれた爆笑クリップも発見できるかも！？',
        type: 'website',
        image: image_url('hasami.jpg'),
        locale: 'ja_JP'
      }
    }
  end
end

app/helpers/clip_posts_helper.rb
module ClipPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-18WCQWTG6Q"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
  
      gtag('config', 'G-18WCQWTG6Q');
    </script>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  </head>

  <body>
  <header class="hidden-big-screen">
  <% if logged_in? %>
    <%= render 'shared/header' %>
  <% else %>
    <%= render 'shared/before_login_header' %>
  <% end %>
  </header>
  <div class="container-fluid">
    <div class="row mb-24">
      <% if logged_in? %>
        <%= render 'shared/left_sidebar' %>
      <% else %>
        <%= render 'shared/before_login_left_sidebar' %>
      <% end %>
      <div class="col-6 full-width">
        <%= yield %>
      </div>
      <%= render 'shared/right_sidebar' %>
    </div>
    </div>
    <footer class="hidden-big-screen">
    <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/compact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
  </head>

  <body>
  <div class="container-fluid">
    <div class="row">
      <%= render 'shared/compact_left_sidebar' %>
      <div class="col-10 full-width">
        <%= yield %>
      </div>
      <% if logged_in? %>
        <%= render 'shared/compact_right_sidebar' %>
      <% else %>
        <%= render 'shared/compact_before_login_right_sidebar' %>
      <% end %>
    </div>
    </div>
    <footer class="hidden-big-screen">
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<div class="fixed-top bg-dark d-flex">
  <div class="col-3">
  </div>
  <div class="col-6 d-flex justify-content-center align-items-center">
    <%= link_to clip_posts_path, class: "text-center font-title text-info font-3 no-decoration" do %>
      <h3>Clip Reactor</h3>
    <% end %>
  </div>
  <div class="col-3 d-flex justify-content-end">
    <button id="dropdownMenuDark" data-bs-toggle="dropdown" aria-expanded="false" class="bg-dark p-0" >
      <%= image_tag "default.png", class: "border border-1 border-danger float-end", size: "40x40" %>
    </button>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuDark">
      <li>
        <%= link_to "新規登録", new_user_path, class: "nav-link simple-button" %>
      </li>
      <li>
        <%= link_to "ログイン", login_path, class: "nav-link simple-button" %>
      </li>
      <li>
        <%= link_to "利用規約", terms_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
      <li>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
      <li>
        <%= link_to "お問い合わせ", contact_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
  </ul>
  </div>
</div>

app/views/shared/_before_login_left_sidebar.html.erb
<div class="col-3 hidden-small-screen bg-light">
  <div class="scroll sticky-top d-flex flex-column">
    <%= link_to clip_posts_path(reset_filter: "reset"), class: "text-center font-title text-info font-3 no-decoration" do %>
      <h3>Clip Reactor</h3>
    <% end %>
  <!-- メニュー -->
    <div class="row bg-light mt-3 p-3">
      <%= link_to clip_posts_path(reset_filter: "reset"), class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-list" %></div>
          <div class="ms-3">クリップ一覧</div>
        </div>
      <% end %>
      <%= link_to likes_clip_posts_path, class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-thumbs-up" %></div>
          <div class="ms-3">いいね一覧</div>
        </div>
      <% end %>
      <%= link_to new_clip_post_path, class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-pencil" %></div>
          <div class="ms-3">新規作成</div>
        </div>
      <% end %>
    </div>
  
  <!-- 検索フォーム(未実装)
    <div class="row bg-light mt-3 pt-3">
      <%= render 'shared/search_form' %>
    </div>
  -->
  
  <!-- プロフィール欄 -->
    <div class="row mt-auto mx-2">
      <div class="menu-item drop-menu btn-primary btn">
        <div class="d-flex align-items-start ms-3">
          <div><%= content_tag :i, nil, class: "fa-solid fa-user" %></div>
          <div class="ms-3">アカウント作成</div>
        </div>
        <ul class="drop-menu-list">
          <li class="drop-menu-item">
            <%= link_to "新規登録", new_user_path %>
          </li>
          <li class="drop-menu-item">
            <%= link_to "ログイン", login_path %>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="text-muted font-size-1">
          <%= link_to "利用規約", terms_path, class: "text-muted-link me-1" %>
          <%= link_to "プライバシーポリシー", privacy_policy_path, class: "text-muted-link me-1" %>
          <%= link_to "お問い合わせ", contact_path, class: "text-muted-link me-1" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_compact_before_login_right_sidebar.html.erb
<div class="col-1">
  <div class="justify-content-end d-flex">
    <div class="d-flex flex-column mt-3 me-4">
      <!-- ログアウトリンク -->
      <div class="flex-item mb-3">
      <%= link_to  new_user_path do %>
          <i class="fa-solid fa-user-plus fa-4x simple-button-purple"></i>
        <% end %>
      </div>
      <div class="flex-item mb-3 mt-3">
        <%= link_to login_path do %>
          <i class="fa-solid fa-arrow-right-to-bracket fa-4x simple-button-purple"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_compact_left_sidebar.html.erb
<div class="col-1 hidden-small-screen">
  <div class="d-flex flex-column mt-3 ms-4">
    <!-- 編集リンク -->
    <div class="flex-item mb-3">
      <%= link_to clip_posts_path do %>
        <i class="fa-solid fa-list fa-4x simple-button-purple"></i>
      <% end %>
    </div>
    <div class="flex-item mb-3">
      <%= link_to likes_clip_posts_path do %>
        <i class="fa-solid fa-thumbs-up fa-4x simple-button-purple"></i>
      <% end %>
    </div>
    <div class="flex-item mb-3 mt-2">
      <%= link_to new_clip_post_path do %>
        <i class="fa-solid fa-pencil fa-4x simple-button-purple"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_compact_right_sidebar.html.erb
<div class="col-1 hidden-small-screen">
  <div class="justify-content-center d-flex">
    <div class="d-flex flex-column mt-3">
      <!-- 編集リンク -->
      <div class="flex-item mb-3">
      <%= link_to logout_path, method: :delete do %>
        <i class="fa-solid fa-arrow-right-from-bracket fa-4x simple-button-purple"></i>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<div id="flash_messages">
<% flash.each do |message_type, message| %>
  <div class="font-6 alert alert-<%= message_type %>"><%= message %></div>
<% end %>
</div>
    

app/views/shared/_footer.html.erb
<div class="fixed-bottom bg-secondary bg-opacity-25 d-flex justify-content-between align-items-center">
  <div class="d-flex justify-content-center align-items-center flex-grow-1">
    <%= link_to clip_posts_path(reset_filter: "reset"), class: "fuller-button purple no-decoration" do %>
      <%= content_tag :i, nil, class: "fa-solid fa-list" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-grow-1">
    <%= link_to likes_clip_posts_path, class: "fuller-button purple no-decoration" do %>
      <%= content_tag :i, nil, class: "fa-solid fa-thumbs-up" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-grow-1">
    <%= link_to new_clip_post_path, class: "fuller-button purple no-decoration" do %>
      <%= content_tag :i, nil, class: "fa-solid fa-pencil" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-grow-1">
    <%= link_to tags_path, class: "fuller-button purple no-decoration" do %>
      <%= content_tag :i, nil, class: "fa-brands fa-searchengin" %>
    <% end %>
  </div>
</div>

app/views/shared/_game_index.html.erb
<div class="text-center mt-3">
  <h5 class="tag-list-title">ゲームで見つける</h5>
</div>
<% tag_names = ClipPost.tags_on(:games).pluck(:name) %>
<% image_records = Image.where(name: tag_names).index_by(&:name) %>

<div class="d-flex flex-wrap justify-content-around">
  <% ClipPost.tags_on(:games).order(name: :asc).each do |tag| %>
    <%= link_to clip_posts_path(tag_game: tag.name), class: "no-decoration shadow-btn m-3" do %>
      <div class="flex-item">
        <% image_record = image_records[tag.name] %>
        <% if image_record && image_record.image_url.present? %>
          <%= image_tag image_record.image_url, size: "144x192" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="fixed-top bg-dark d-flex">
  <div class="col-3">
  </div>
  <div class="col-6 d-flex justify-content-center align-items-center">
    <%= link_to clip_posts_path(reset_filter: "reset"), class: "text-center font-title text-info font-3 no-decoration" do %>
      <h3>Clip Reactor</h3>
    <% end %>
  </div>
  <div class="col-3 d-flex justify-content-end">
    <button id="dropdownMenuDark" data-bs-toggle="dropdown" aria-expanded="false" class="bg-dark p-0" >
      <%= image_tag current_user.stamp_url, class: "border border-1 border-danger float-end", size: "40x40" %>
    </button>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuDark">
      <li>
        <%= link_to "ログアウト", logout_path, data: { method: "delete" }, class: "nav-link simple-button text-white" %>
      </li>
      <li>
        <%= link_to "利用規約", terms_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
      <li>
        <%= link_to "プライバシーポリシー", privacy_policy_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
      <li>
        <%= link_to "お問い合わせ", contact_path, class: "nav-link simple-button font-size-1 text-muted" %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_left_sidebar.html.erb
<div class="col-3 hidden-small-screen bg-light">
  <div class="scroll sticky-top d-flex flex-column">
    <%= link_to clip_posts_path(reset_filter: "reset"), class: "text-center font-title text-info font-3 no-decoration" do %>
      <h3>Clip Reactor</h3>
    <% end %>
  <!-- メニュー -->
    <div class="row bg-light mt-3 p-3">
      <%= link_to clip_posts_path(reset_filter: "reset"), class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-list" %></div>
          <div class="ms-3">クリップ一覧</div>
        </div>
      <% end %>
      <%= link_to likes_clip_posts_path, class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-thumbs-up" %></div>
          <div class="ms-3">いいね一覧</div>
        </div>
      <% end %>
      <%= link_to new_clip_post_path, class: "mt-3 fuller-button purple no-decoration" do %>
        <div class="d-flex align-items-start">
          <div><%= content_tag :i, nil, class: "fa-solid fa-pencil" %></div>
          <div class="ms-3">新規作成</div>
        </div>
      <% end %>
    </div>
  
  <!-- 検索フォーム(未実装)
    <div class="row bg-light mt-3 pt-3">
      <%= render 'shared/search_form' %>
    </div>
  -->
  
  <!-- プロフィール欄 -->
    <div class="row bg-light p-2 mt-auto">
      <div class="menu-item drop-menu">
        <div class="d-flex align-items-start">
          <div><%= image_tag current_user.stamp_url, class: "", size: "50x50" %></div>
          <div class="ms-3 align-self-center">プロフィール</div>
        </div>
        <ul class="drop-menu-list">
          <li class="drop-menu-item">
            <%= link_to "ログアウト", logout_path, data: { method: "delete" } %>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="text-muted font-size-1">
          <%= link_to "利用規約", terms_path, class: "text-muted-link me-1" %>
          <%= link_to "プライバシーポリシー", privacy_policy_path, class: "text-muted-link me-1" %>
          <%= link_to "お問い合わせ", contact_path, class: "text-muted-link me-1" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_right_sidebar.html.erb
<div class="col-3 bg-light hidden-small-screen">
  <%= render 'shared/tag_index' %>
</div>

app/views/shared/_search_form.html.erb
<%= search_form_for @q || ClipPost.ransack(params[:q]), url: clip_posts_path do |f| %>
  <div class="input-group">
    <%= f.search_field :tags_name_cont, class: 'form-control', placeholder: "タグを入力してください" %>
  </div>
  <div class="input-group-append text-center">
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_tag_index.html.erb
<div class="accordion accordion-flush" id="accordionFlush">
  <div class="accordion-item mt-3 bg-light">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="tag-title-acordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        配信者で見つける
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlush">
      <div class="accordion-body">
        <% ClipPost.tags_on(:streamers).order(name: :asc).each do |streamer| %>
          <% streamer_image = @streamers_image[streamer.name] %>
          <div class="flex-item ms-1 mt-3 bg-white">
            <%= link_to clip_posts_path(tag_streamer: streamer.name), class: "no-decoration row shadow-btn rounded-3", style: "background: #{streamer_image&.image_color}07;" do %>
              <div class="col-3">
                <% if streamer && streamer_image&.image_url.present? %>
                  <%= image_tag streamer_image.image_url, class: "rounded-circle", size: "50x50" %>
                <% else %>
                  <%= image_tag "default.png", class: "rounded_circle", size: "50x50" %>
                <% end %>
              </div>
              <div class="col-9 h2 font-5 text-muted">
                <%= streamer.name %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="accordion-item bg-light">
    <h2 class="accordion-header" id="flush-headingTwo">
      <button class="tag-title-acordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        ゲームで見つける
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlush">
      <div class="accordion-body d-flex flex-wrap">
        <% @games.each do |game| %>
          <%= link_to clip_posts_path(tag_game: game.name), class: "no-decoration shadow-btn m-3" do %>
            <div class="flex-item">
              <% if game && game.image_url.present? %>
                <%= image_tag game.image_url, size: "144x192" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="accordion-item bg-light">
    <h2 class="accordion-header" id="flush-headingThree">
      <button class="tag-title-acordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
        イベントで見つける
      </button>
    </h2>
    <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlush">
      <div class="accordion-body d-flex flex-wrap">
        <% @tags.each do |tag| %>
          <div class="flex-item ms-1">
          <%= link_to clip_posts_path(tag_name: tag.name), class: "no-decoration" do %>
            <p class="tag_wrapper" style="font-size: 12px"><%= tag %></p>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_title_bar.html.erb
<div class="d-flex justify-content-center align-items-center border-bottom border-warning border-3 bg-light" style="height: 60px;">
  <div class="h5 font-2"><%= title %></div>
</div>
<%= render 'shared/flash_message' %>