config/routes.rb
Rails.application.routes.draw do
  root to: "clip_posts#index"
  # Sitemap
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/clipreactor/sitemaps/sitemap.xml.gz')

  
  # Test Controller
  get 'test', to: 'test#new'

  # Clip Posts
  resources :clip_posts do
    resources :comments, shallow: true, only: %i[create destroy]
    collection do
      get :likes
      get :get_clip
      get :update_video
    end
  end

  # Tags
  resources :tags do
    collection do
      get :auto_complete_streamers
      get :auto_complete_tags
    end
  end

  # Users
  resources :users, only: %i[new create] do
    collection do
      get :get_user_stamp
    end
  end

  # Likes and Comment Likes
  resources :likes, only: %i[create destroy]
  resources :comment_likes, only: %i[create destroy]

  # Static Pages
  get 'terms', to: 'satatic_pages#terms'
  get 'privacy_policy', to: 'satatic_pages#privacy_policy'

  # Contacts
  get 'contact', to: 'contacts#new'
  post 'contact', to: 'contacts#create'
  get 'contact/success', to: 'contacts#success'

  # User Sessions
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new; end

  def create
    if params[:contact_text].blank?
      flash[:danger] = I18n.t('contacts.flash.danger')
      render :new
    else
      ContactMailer.with(user: current_user, email: params[:email], contact_text: params[:contact_text]).contact_email.deliver_now
      redirect_to contact_success_path
    end
  end

  def success; end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contacts/new.html.erb
<% set_meta_tags noindex: true %>
<%= render 'shared/title_bar', title: "ご要望・お問い合わせ" %>
<div class="container border-dark border-1 border mt-2">
  <div class="text-center h5 mt-2">内容の入力</div>
  <%= form_with url: contact_path, method: :post do |form| %>

  <!-- メールアドレス -->
  <div class="mb-2 row mt-4">
    <div class="col-9 pr-0">
      <%= form.label :email, "メールアドレス" %>
      <%= form.email_field :email, class: "form-control", placeholder: "返信を希望する場合は入力してください" %>
    </div>
  </div>

    <!-- お問い合わせ内容の入力 -->
    <div class="mb-2">
      <%= form.label :contact_text, "ご要望・お問い合わせ" %>
      <%= form.text_area :contact_text, class: "form-control", placeholder: "ご要望・お問い合わせ内容を入力してください" %>
    </div>

    <!-- 送信ボタン -->
    <div class="d-flex justify-content-center mb-3">
      <%= form.button "送信する", type: "submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/contacts/success.html.erb
<% set_meta_tags noindex: true %>
<%= render 'shared/title_bar', title: "お問い合わせ完了" %>
<div class="container border-dark border-1 border mt-2">
  <div class="text-center h5 mt-2"><p>ご要望・お問い合わせありがとうございました。</p></div>
  <p>お問い合わせへの回答に関しましては、ご入力いただいたメールアドレスにご回答いたします。</p>
  <div class="d-flex justify-content-center">
    <%= link_to "閉じる", clip_posts_path, class: "btn btn-primary btn-sm mb-1" %>
  </div>
</div>